In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import scipy.io
import numpy as np
import tensorflow as tf



Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


4
(4, 1, 2)


In [ ]:
def initialize_parameter(n_x,n_h,n_y): 
  np.random.seed(1)

  W1 = np.random.rand(n_h,n_x) *0.01
  W2 = np.random.rand(n_y,n_h) *0.01
  # to make sure if the shape is right
  assert(W1.shape == (n_h,n_x))
  assert(W2.shape == (n_y,n_h))

  parameters = {"W1": W1, "W2":W2}
  return parameters

In [ ]:
parameters = initialize_parameter(2,2,1)
print("W1 = " + str(parameters["W1"]))
print("W2 = " + str(parameters["W2"]))


W1 = [[4.17022005e-03 7.20324493e-03]
 [1.14374817e-06 3.02332573e-03]]
W2 = [[0.00146756 0.00092339]]


In [ ]:
def initialize_parameters_deep(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):

        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l - 1]) * 0.01

        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))

        
    return parameters

In [ ]:
parameters = initialize_parameters_deep([5,4,3])
print("W1 = " + str(parameters["W1"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]


In [ ]:


# with tf.compat.v1.variable_scope('cltdevelop'):
#     var_1 = tf.get_variable('var_1', shape=[1, ])
# with tf.compat.v1.variable_scope('cltdevelop', reuse=True):
#     var_2 = tf.get_variable('var_1', shape=[1,])
# print(var_1.name)
# print(var_2.name)

# with tf.name_scope('cltdevelop'):
#   var_1 = tf.Variable(initial_value=[0], name='var_1')
#   var_2 = tf.Variable(initial_value=[0], name='var_1')
#   var_3 = tf.Variable(initial_value=[0], name='var_1')

# print(var_1.name)
# print(var_2.name)
# print(var_3.name)

with tf.name_scope('cltdevelop'):
    var_1 = tf.Variable(initial_value=[0], name='var_1')
    var_2 = tf.compat.v1.get_variable(name='var_2', shape=[1, ])
with tf.compat.v1.variable_scope('aaa'):
    var_3 = tf.Variable(initial_value=[0], name='var_3')
    var_4 = tf.compat.v1.get_variable(name='var_4', shape=[1, ])

print(var_1.name)
print(var_2.name)
print(var_3.name)
print(var_4.name)


cltdevelop/var_1:0
var_2:0
aaa/var_3:0
aaa/var_4:0


In [ ]:
def gcn_layer(A_hat, D_hat, X, W):

    return np.array(tf.nn.relu(D_hat**-1 * A_hat * X * W))


H_1 = gcn_layer(A_hat, D_hat, A, W_1)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)

In [ ]:
a = scipy.io.loadmat("/content/gdrive/My Drive/Sub/nonflipped/keep_30/Subpre/1.mat") 
# new = a['freqcohpersub']
new = a['M']
# new = nor['freqcohpersub'] 
Patient = []
P = []
for i in range (30):
    tmp = []
    for j in range (50):
        tmp.append(new[0,i][0,j])
    Patient.append(tmp)
# all range of herz of all patients' data   24,30,116,116       
Patient = np.array(Patient) 
print(Patient.shape)

(30, 50, 116, 116)


In [ ]:
#这个把 24个病人的 pre post fu 串到一起 例子：病人1 的50pre + 50post +50fu = 150个   (30, 150, 116, 116)

for Num in range(1,25):
  pre = scipy.io.loadmat('/content/gdrive/My Drive/Sub/nonflipped/keep_30/Subpre/' + str(Num) + '.mat') 
  post = scipy.io.loadmat('/content/gdrive/My Drive/Sub/nonflipped/keep_30/Subpost/' + str(Num) + '.mat') 
  fu = scipy.io.loadmat('/content/gdrive/My Drive/Sub/nonflipped/keep_30/Subfu/' + str(Num) + '.mat') 
  # if 'y' in nor:
  #   print(Num)
  # tmp1 = pre['freqcohpersub'] 
  # tmp2 = post['freqcohpersub'] 
  # tmp3 = fu['freqcohpersub'] 
  tmp1 = pre['M'] 
  tmp2 = post['M'] 
  tmp3 = fu['M'] 

  Patient = []
  P = []
  for i in range (30):
      tmp = []
      for j in range (50):
          tmp.append(tmp1[0,i][0,j])
      Patient.append(tmp)
  # all range of herz of all patients' data   24,30,116,116       
  Patient1 = np.array(Patient) 
  # print(Num)
  # print(Patient1.shape)  

  Patient = []
  P = []
  for i in range (30):
      tmp = []
      for j in range (50):
          tmp.append(tmp2[0,i][0,j])
      Patient.append(tmp)
  # all range of herz of all patients' data   24,30,116,116       
  Patient2 = np.array(Patient) 
  # print(Num)
  # print(Patient2.shape) 

  Patient = []
  P = []
  for i in range (30):
      tmp = []
      for j in range (50):
          tmp.append(tmp3[0,i][0,j])
      Patient.append(tmp)
  # all range of herz of all patients' data   24,30,116,116       
  Patient3 = np.array(Patient) 
  # print(Num)
  # print(Patient3.shape) 

  print(Num)
  PATIENT = np.concatenate((Patient1,Patient2,Patient3), axis = 1)   #形状为(30, 150, 116, 116)
  np.save('/content/gdrive/My Drive/Newdata/ordered_by_patient/connectivity/nonflipped_keep30_150_'+str(Num), PATIENT)



# Numpy simple GCN

In [ ]:
a = np.load('/content/gdrive/My Drive/Newdata/ordered_by_patient/connectivity/nonflipped_keep30_150_1.npy')
a = np.reshape(a,(150,30,116,116))

In [ ]:
b = np.load('/content/gdrive/My Drive/strength/nonflipped/keep_30/three/1.npy')
b = np.reshape(b,(150,30,116))
print(b.shape)

(150, 30, 116)


In [ ]:
X = b[0,0]  #为初始输入值
X = np.reshape(X,(116,1))


In [ ]:
A = a[0,0] #就是邻接矩阵
c = tf.where(b>0,1,0) #所有大于0的都替换成1用来表示两个node之间有连接
I = np.matrix(np.eye(A.shape[0])) #单位矩阵 
A_hat = A + I 
# 生成对应的度矩阵
D_hat = np.array(np.sum(c, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat)) 

In [ ]:
# 初始化随机生成两层权重数值
W_1 = np.random.normal(  # Drawn samples from the parameterized normal distribution.返回形状为（116，4）的参数化的正态分布值
    loc=0, scale=1, size=(A.shape[0], 4))
print(W_1.shape)
W_2 = np.random.normal(
    loc=0, scale=1,size=(W_1.shape[1], 2)) #生成（4,2）形状的正态分布矩阵
print(W_2.shape)
# print((D_hat**-1 * A_hat * X).shape)
def gcn_layer(A_hat, D_hat, X, W):
    return np.array(tf.nn.relu(D_hat**-1 * A_hat * X * W))


H_1 = gcn_layer(A_hat, D_hat, A, W_1)
# H_1 = np.array(H_1)
# print(H_1)
# print((D_hat**-1*A_hat).shape)
# print(((D_hat**-1*A_hat)*H_1).shape)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)

# print(H_2)

(116, 4)
(4, 2)


# 真的写

In [ ]:
class SpectralRule(HybridBlock):
    def __init__(self, A, in_units, out_units, activation, **kwargs):
        super().__init__(**kwargs)
        I = nd.eye(*A.shape)
        A_hat = A.copy() + I
        D = nd.sum(A_hat, axis=0)
        D_inv = D**-0.5
        D_inv = nd.diag(D_inv)
        A_hat = D_inv * A_hat * D_inv
        
        self.in_units, self.out_units = in_units, out_units
        
        with self.name_scope():
            self.A_hat = self.params.get_constant('A_hat', A_hat)
            self.W = self.params.get('W', shape=(self.in_units, self.out_units))
            if activation == 'ident':
                self.activation = lambda X: X
            else:
                self.activation = Activation(activation)
    def hybrid_forward(self, F, X, A_hat, W):
        aggregate = F.dot(A_hat, X)
        propagate = self.activation(
            F.dot(aggregate, W))
        return propagate